In [21]:
#==========using basic python
temparture=[32,35,38,40,42,45]
voltage=[400,395,390,385,380,375]
current=[20,22,25,28,30,32]
charge=[95,88,80,70,60,48]
for i in range(6):
  print(temparture[i],voltage[i],current[i],charge[i])
# Check temperature
for i in range(6):
    if temparture[i] > 40:
        print("High temp")
    else:
        print("Temperature normal")
#identify low battery
for i in range(6):
    if charge[i] < 50:
        print("Time", i, "h: Low Battery Alert")
    else:
        print("Time", i, "h: Battery Charge Normal")
#create a function
def battery_status(charge):
    if charge > 70:
        return "High"
    elif charge >= 50:
        return "Medium"
    else:
        return "Low"






32 400 20 95
35 395 22 88
38 390 25 80
40 385 28 70
42 380 30 60
45 375 32 48
Temperature normal
Temperature normal
Temperature normal
Temperature normal
High temp
High temp
Time 0 h: Battery Charge Normal
Time 1 h: Battery Charge Normal
Time 2 h: Battery Charge Normal
Time 3 h: Battery Charge Normal
Time 4 h: Battery Charge Normal
Time 5 h: Low Battery Alert


In [32]:
#===============numpy

import numpy as np

# Battery data
D = np.array([
    [32, 400, 20, 95],
    [35, 395, 22, 88],
    [38, 390, 25, 80],
    [40, 385, 28, 70],
    [42, 380, 30, 60],
    [45, 375, 32, 48]
])

print("Battery Data:")
print(D)

print("\nShape of array:")
print(D.shape)

print("Number of rows:", D.shape[0])
print("Number of columns:", D.shape[1])
# Calculate average of each parameter

average_temperature = np.mean(D[:, 0])
average_voltage = np.mean(D[:, 1])
average_current = np.mean(D[:, 2])
average_charge = np.mean(D[:, 3])

print("Average Temperature =", average_temperature, "°C")
print("Average Voltage =", average_voltage, "V")
print("Average Current =", average_current, "A")
print("Average Charge =", average_charge, "%")

# Extract temperature column
temperature = D[:, 0]

# Find maximum and minimum
maximum_temperature = np.max(temperature)
minimum_temperature = np.min(temperature)

print("Maximum Temperature =", maximum_temperature, "°C")
print("Minimum Temperature =", minimum_temperature, "°C")
# Extract voltage column
voltage = D[:, 1]

print("Voltage Column:")
print(voltage)
#Identify high temperature readings
high_temperature = D[D[:, 0] > 40, 0]

print("High Temperatures:")
print(high_temperature)
# Identify low battery readings
low_battery = D[D[:, 3] < 50]

print("Low Battery Readings:")
print(low_battery)



Battery Data:
[[ 32 400  20  95]
 [ 35 395  22  88]
 [ 38 390  25  80]
 [ 40 385  28  70]
 [ 42 380  30  60]
 [ 45 375  32  48]]

Shape of array:
(6, 4)
Number of rows: 6
Number of columns: 4
Average Temperature = 38.666666666666664 °C
Average Voltage = 387.5 V
Average Current = 26.166666666666668 A
Average Charge = 73.5 %
Maximum Temperature = 45 °C
Minimum Temperature = 32 °C
Voltage Column:
[400 395 390 385 380 375]
High Temperatures:
[42 45]
Low Battery Readings:
[[ 45 375  32  48]]


In [34]:
#=================linear algebra
import numpy as np

# Matrix A
A = np.array([
    [2, 1],
    [1, 3]
])

# Matrix X
X = np.array([
    [40],
    [25]
])
# 1. Calculate Y = AX
Y = A @ X
print("1. Y = AX")
print(Y)
# 2. Transpose of A
transpose_A = A.T

print("\n2. Transpose of A")
print(transpose_A)
# 3. Determinant of A
det_A = np.linalg.det(A)
print("\n3. Determinant of A")
print(det_A)
# 4. Inverse of A
inverse_A = np.linalg.inv(A)
print("\n4. Inverse of A")
print(inverse_A)
# 5. Solve the equations
# 2x + y = 100
# x + 3y = 120
B = np.array([
    100,
    120
])

solution = np.linalg.solve(A, B)

print("\n5. Solution of AX = B")

print("x =", solution[0])
print("y =", solution[1])


1. Y = AX
[[105]
 [115]]

2. Transpose of A
[[2 1]
 [1 3]]

3. Determinant of A
5.000000000000001

4. Inverse of A
[[ 0.6 -0.2]
 [-0.2  0.4]]

5. Solution of AX = B
x = 36.0
y = 28.0


In [35]:
#=================calculas
# Battery charge function
def C(t):
    return 100 - 2*t - 0.5*(t**2)

# Rate of change / derivative
def dC_dt(t):
    return -2 - t

# Calculate discharge rate
rate_2 = dC_dt(2)
rate_5 = dC_dt(5)

print("Rate of change: dC/dt = -2 - t")

print("Discharge rate at t = 2:", rate_2, "% per hour")
print("Discharge rate at t = 5:", rate_5, "% per hour")

# Interpretation
if abs(rate_5) > abs(rate_2):
    print("Battery is losing charge at an increasing rate.")


Rate of change: dC/dt = -2 - t
Discharge rate at t = 2: -4 % per hour
Discharge rate at t = 5: -7 % per hour
Battery is losing charge at an increasing rate.
