In [1]:
import numpy as np
print(np.random.rand())
print(np.random.rand(5))
print(np.random.randint(1, 11, 5))
subjects = ["DBMS", "Python", "Java", "ML"]
print(np.random.choice(subjects))
print(np.random.normal(50, 10, 5))
print(np.random.uniform(10, 20, 5))
print(np.random.binomial(1, 0.5))
print(np.random.binomial(10, 0.7))
print(np.random.poisson(4, 5))
print(np.random.exponential(2, 5))

0.5893060517763352
[0.71278048 0.17644838 0.79046391 0.57191953 0.87223594]
[9 7 4 4 8]
Java
[41.57790067 37.22187245 57.21609282 60.7196215  38.71541041]
[17.59741896 13.75738547 16.20335839 15.71961872 14.85445451]
1
8
[4 8 8 7 6]
[2.8726074  0.49712845 0.82281201 1.82727428 0.4492853 ]


In [2]:
import numpy as np
marks = np.array([75, 82, 90, 68, 95, 88, 79])
print("Original Array:", marks)
print("Sorted Array:", np.sort(marks))
print("\nSum:", np.sum(marks))
print("Mean:", np.mean(marks))
print("Median:", np.median(marks))
print("Maximum:", np.max(marks))
print("Minimum:", np.min(marks))
print("Range:", np.ptp(marks))
print("Standard Deviation:", np.std(marks))
print("Variance:", np.var(marks))
print("Index of Maximum:", np.argmax(marks))
print("Index of Minimum:", np.argmin(marks))
print("25th Percentile:", np.percentile(marks, 25))
print("50th Percentile:", np.percentile(marks, 50))
print("75th Percentile:", np.percentile(marks, 75))

Original Array: [75 82 90 68 95 88 79]
Sorted Array: [68 75 79 82 88 90 95]

Sum: 577
Mean: 82.42857142857143
Median: 82.0
Maximum: 95
Minimum: 68
Range: 27
Standard Deviation: 8.633111388421788
Variance: 74.53061224489797
Index of Maximum: 4
Index of Minimum: 3
25th Percentile: 77.0
50th Percentile: 82.0
75th Percentile: 89.0


In [3]:
import numpy as np
arr = np.array([10, 20, 30, 40])
print(arr)

[10 20 30 40]


In [4]:
import numpy as np
arr = np.array([1, 4, 9, 16, 25])
print("Original Array:", arr)
print("\nSquare Root:", np.sqrt(arr))
print("Square:", np.square(arr))
print("Cube:", np.power(arr, 3))
arr2 = np.array([-5, -10, 15, -20, 25])
print("\nAbsolute Value:", np.abs(arr2))
print("\nExponential:", np.exp(arr))
print("\nNatural Log:", np.log(arr))
print("Log Base 10:", np.log10(arr))
print("\nSine:", np.sin(arr))
print("Cosine:", np.cos(arr))
print("Tangent:", np.tan(arr))
decimal = np.array([2.34, 4.67, 8.91, 6.28])
print("\nRounded Values:", np.round(decimal))
print("Ceiling:", np.ceil(decimal))
print("Floor:", np.floor(decimal))

Original Array: [ 1  4  9 16 25]

Square Root: [1. 2. 3. 4. 5.]
Square: [  1  16  81 256 625]
Cube: [    1    64   729  4096 15625]

Absolute Value: [ 5 10 15 20 25]

Exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]

Natural Log: [0.         1.38629436 2.19722458 2.77258872 3.21887582]
Log Base 10: [0.         0.60205999 0.95424251 1.20411998 1.39794001]

Sine: [ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]
Cosine: [ 0.54030231 -0.65364362 -0.91113026 -0.95765948  0.99120281]
Tangent: [ 1.55740772  1.15782128 -0.45231566  0.30063224 -0.13352641]

Rounded Values: [2. 5. 9. 6.]
Ceiling: [3. 5. 9. 7.]
Floor: [2. 4. 8. 6.]


In [5]:
import numpy as np

a = np.array([10,20,30])
b = np.array([2,4,5])
print("Addition:", a+b)
print("Subtraction:", a-b)
print("Multiplication:", a*b)
print("Division:", a/b)
print("Floor Division:", a//b)
print("Modulus:", a%b)
print("Power:", a**2)

Addition: [12 24 35]
Subtraction: [ 8 16 25]
Multiplication: [ 20  80 150]
Division: [5. 5. 6.]
Floor Division: [5 5 6]
Modulus: [0 0 0]
Power: [100 400 900]


In [6]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[0:6])
print(arr[:3])
print(arr[2:])
print(arr[0:6:2])


[1 2 3 4 5]
[1 2 3]
[3 4 5]
[1 3 5]


In [7]:
arr_3d = np.array([1,2,3,4,5,6,7,8])
new_arr_3d = arr_3d.reshape(2,2,2)
print(new_arr_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [8]:
arr = np.array([1, 2, 3, 4, 5, 6])
new_arr_1 = np.reshape(arr,(3,2))
print(new_arr_1)

[[1 2]
 [3 4]
 [5 6]]


In [9]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6,7,8])
new_arr = arr.reshape(2, 4)
print(new_arr)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:

arr = np.array([
    [[1, 2, 3],
     [4, 2, 3]],

    [[1, 2, 7],
     [1,5,6]]
])

print(arr)
print(arr.ndim)   # Number of dimensions
print(arr.shape)  # (Layers, Rows, Columns)
print(arr.size)   # Total number of elements
print(arr[0])        # First layer
print(arr[1])        # Second layer
print(arr[0][1])     # Second row of first layer
print(arr[1][0][0])  # Element 9

[[[1 2 3]
  [4 2 3]]

 [[1 2 7]
  [1 5 6]]]
3
(2, 2, 3)
12
[[1 2 3]
 [4 2 3]]
[[1 2 7]
 [1 5 6]]
[4 2 3]
1


In [11]:
arr=np.array([[1,7,2],[1,2,5]])
print(arr.size)
print(arr.dtype)
print(arr.T)
print(arr.ndim)

6
int64
[[1 1]
 [7 2]
 [2 5]]
2


In [12]:
arr=np.full((3,4),21)
print(arr)

[[21 21 21 21]
 [21 21 21 21]
 [21 21 21 21]]


In [13]:
arr=np.eye(9)
print(arr)

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [14]:
arr=np.linspace(1, 15, 3)
print(arr)

[ 1.  8. 15.]


In [15]:
arr = np.array([[1,2,3,4], [4,5,6,7]])
print(arr.shape)
print(arr.size)

(2, 4)
8


In [16]:
arr = np.arange(1,17)
print(arr.reshape(4,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [17]:
arr = np.arange(1,15)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [18]:
arr = np.zeros((4,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
import numpy as np
arr = np.array([10, 20, 30, 40])
print(arr)

[10 20 30 40]
